### ISSUE TITLE
Add Meme template svg

### ISSUE THREAD

**Issue by nimit2801** [HackClubNUV/kendi-hundi-si#2]
Template here

<img src="https://user-images.githubusercontent.com/53462249/150572084-fa884f33-16f5-4cb3-be76-56e3254fdc5e.jpg" data-canonical-src="https://gyazo.com/eb5c5741b6a9a16c692170a41a49c858.png" width="300" height="400" />

**Comment by ashwinadiga01** [comment]
Hey @nimit2801! I'm working on this rn!

**Comment by nimit2801** [comment]
LGTM! works ✅
